Update to test LDC v1.25.0 with backtrace support

diff --git a/ldc/APKBUILD b/ldc/APKBUILD
--- a/ldc/APKBUILD
+++ b/ldc/APKBUILD
@@ -1,66 +1,134 @@
 # Contributor: Mathias LANG <pro.mathias.lang@gmail.com>
 # Maintainer: Mathias LANG <pro.mathias.lang@gmail.com>
 pkgname=ldc
-pkgver=1.18.0
+pkgver=1.25.0_git
+_pkgrealver=1.25.0-beta1
 pkgrel=1
 pkgdesc="The LLVM-based D Compiler"
-url="https://github.com/ldc-developers/ldc"
-# Bootstrapping was done with an upstream-provided package,
-# with only x86_64 available
-# Once we can use GDC for bootstrapping, this can be "all"
-arch="x86_64"
-license="BSD-3-Clause AND BSL-1.0 AND (Artistic-1.0 OR GPL-2.0-or-later) AND NCSA AND MIT"
-depends="libexecinfo tzdata"
-makedepends="bash chrpath cmake curl-dev diffutils dlang-compiler gdb grep llvm9-dev llvm9-static libedit-dev libexecinfo-static py-pip zlib-dev"
+url="https://github.com/ldc-developers/ldc -b backtrace"
+# LDC does not support host compiling on most of the architecture Alpine supports
+arch="x86_64 aarch64"
+license="BSD-3-Clause AND BSL-1.0 AND ( Artistic-1.0 OR GPL-2.0-or-later ) AND NCSA AND MIT"
+depends="llvm-libunwind-dev tzdata"
+makedepends="git chrpath cmake curl-dev diffutils gdmd llvm10-dev llvm10-static
+	libedit-dev zlib-dev"
+checkdepends="bash gdb grep llvm10-test-utils"
 # A user might want to install the '-runtime' subpackage when they have
 # a dynamically-linked D program.
-subpackages="$pkgname-runtime $pkgname-static"
-provides="dlang-compiler"
-source="https://github.com/ldc-developers/ldc/releases/download/v$pkgver/ldc-$pkgver-src.tar.gz
-		01-stdio-fseek.patch
-		02-conf.patch
-        03-coverage.patch
-        "
-builddir="$srcdir/ldc-$pkgver-src/"
+subpackages="
+	$pkgname-runtime
+	$pkgname-static
+	$pkgname-dbg
+	$pkgname-bash-completion:bashcomp:noarch"
+source="
+	01-conf.patch
+	"
+builddir="$srcdir/ldc/"
+
+prepare() {
+    mkdir -p $srcdir
+
+    if [ ! -d $builddir ]; then
+        git clone https://github.com/kinke/ldc.git -b backtrace $builddir || return 1
+        cd $builddir
+    else
+        cd $builddir
+        git fetch || return 1
+    fi
+
+    git submodule sync || return 1
+    git submodule update --init || return 1
+
+    default_prepare
+}
 
 build() {
+	# Note: The CI was running into OOM while building this package
+	# See https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/14364#note_122336
+	case "$CARCH" in x86*)
+		export MAKEFLAGS="$MAKEFLAGS -j$((JOBS<4 ? JOBS : 4))"
+		export DFLAGS="$DFLAGS -lowmem"
+		;;
+	esac
+	# First, build LDC using GDC
+	mkdir -p "$builddir/stage1"
 	if [ "$CBUILD" != "$CHOST" ]; then
 		CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
 	fi
+	unset DFLAGS
+	cmake \
+		-DCMAKE_CXX_FLAGS="$CXXFLAGS" \
+		-DCMAKE_C_FLAGS="$CFLAGS" \
+		-DD_COMPILER='gdmd' \
+		$CMAKE_CROSSOPTS -S "$builddir" -B "$builddir/stage1"
+	make -C "$builddir/stage1"
+
+	# Then, self-build
+	if [ "$CBUILD" != "$CHOST" ]; then
+		CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
+	fi
+	# Don't use None buildtype for now, see
+	# https://github.com/ldc-developers/ldc/issues/3386#issuecomment-603370855
 	cmake \
 		-DCMAKE_INSTALL_PREFIX=/usr \
 		-DCMAKE_INSTALL_LIBDIR=lib \
 		-DBUILD_SHARED_LIBS=True \
-		-DCMAKE_BUILD_TYPE=Release \
+		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
 		-DCMAKE_CXX_FLAGS="$CXXFLAGS" \
 		-DCMAKE_C_FLAGS="$CFLAGS" \
+		-DD_COMPILER="$builddir/stage1/bin/ldmd2" \
 		$CMAKE_CROSSOPTS "$builddir"
 	make
 
-	# CMake added the rpaths to the shared libs - strip them
+	# Build the test runners
+	make all-test-runners
+
+	# CMake added the rpaths to the shared libs (of stage1!) - strip them
 	chrpath -d "$builddir"/lib/*.so*
+	chrpath -d \
+		"$builddir"/bin/ldc2 \
+		"$builddir"/bin/ldmd2 \
+		"$builddir"/bin/ldc-build-runtime \
+		"$builddir"/bin/ldc-prune-cache
 }
 
 check() {
-	# Dependency to lit-test
-	# python -m pip install --user lit
+	# Find the libraries we just built as final (not stage1!)
+	export LD_LIBRARY_PATH="$builddir"/lib
 
-	# Note: The testsuite does not parallelize well, as the `clean` target get run in parallel.
-	# Hence `-j${JOBS}` was left out on purpose
+	case "$CARCH" in
+		# Math & numeric related tests fail due to https://github.com/ldc-developers/ldc/issues/3270#issuecomment-613132406
+		# druntime-test-thread fails due to https://github.com/ldc-developers/ldc/issues/3403
+		aarch64)
+			_tests_ignore="|core\.thread\.fiber|std.*math.*|std\.numeric.*|std\.format|std\.algorithm\.sorting.*|druntime-test-thread|std\.complex.*"
+			;;
+		# https://github.com/ldc-developers/ldc/issues/3404
+		x86)
+			_tests_ignore="|druntime-test-thread"
+			;;
+	esac
+
+
+	# Note: The testsuite does not parallelize well, as the 'clean' target get run in parallel.
+	# Hence '-j${JOBS}' was left out on purpose
 	#
 	# - dmd-testsuite takes too long to run and has more to do with language checks
 	#	which are less relevant to us than platform integration tests
 	# - lit-test disabled because 'TEST 'LDC :: debuginfo/print_gdb.d' FAILED'
 	#	Something to do with TLS variables not being printable in GDB
-	# - 'druntime-test-shared' fails, probably because it is using `Object.factory`
+	# - 'druntime-test-shared' fails, probably because it is using 'Object.factory'
 	# - 'druntime-test-stdcpp' fails for an unknown reason and is temporarily disabled
 	# - 'druntime-test-exceptions' fails for an unknown reason and is temporarily disabled
-	# ctest --output-on-failure -E "dmd-testsuite|lit-tests|druntime-test-exceptions|druntime-test-shared|druntime-test-stdcpp"
-    :
+	ctest --output-on-failure -E "dmd-testsuite|lit-tests|druntime-test-exceptions|druntime-test-shared|druntime-test-stdcpp$_tests_ignore"
 }
 
 package() {
-	make DESTDIR="$pkgdir" install
+	depends="$pkgname-static=$pkgver-r$pkgrel"
+	# Use -j1, the install is flaky with too many build jobs
+	make -j1 DESTDIR="$pkgdir" install
+
+	mkdir -p "$pkgdir"/usr/share/bash-completion
+	mv "$pkgdir"/etc/bash_completion.d "$pkgdir"/usr/share/bash-completion/completions
 }
 
 runtime() {
@@ -85,7 +153,12 @@ static() {
 	mv "$pkgdir"/usr/lib/*.a "$subpkgdir/usr/lib/"
 }
 
-sha512sums="fe7529c33d0e43dfb71f474dfa381b88ee476b70933c8f80fc063d9a015df24a75e2b607a7242cc4b9cd4b6ac7559aec8f2883016bf7252342742322fcccbd4d  ldc-1.18.0-src.tar.gz
-20d6bb560867052edeed6005e15473dae25c62002c7bd47f0e37610ffd5e94a50b49244c2a9b814f4858babca403f120ae6028cd86f964dd4734736eda068536  01-stdio-fseek.patch
-eb86e4be0ecf72aaabbd5608c8056bb9cede035895e766330b6d14f14c06dc513fcecc1b6e56ab6fc9fc26c220a689cc8b1394a30a319189c414f1e067c1d983  02-conf.patch
-0ce6ed90ea412f08a44b8d2aca061935904f6cb64d47526fb1b57a000113b5368956d79d40e240727594a411f81a2099a0ebbb91979fe6568fa250e52634c91d  03-coverage.patch"
+bashcomp() {
+	depends=""
+	pkgdesc="Bash completions for $pkgname"
+	install_if="$pkgname=$pkgver-r$pkgrel bash-completion"
+
+	amove usr/share/bash-completion/completions
+}
+
+sha512sums="e4187823e4ad00abbec107b53aca5c1478d8500d189bcfc57a6d5607210ac0319802015b0b72484953f049192e58887095f53773903480b2975ad8c19a242815  01-conf.patch"
